### ISSUE TITLE
Pack fails on Windows, Luanti 5.8.0

### ISSUE THREAD

**Issue by mark-wiemer** [GefullteTaubenbrust2/Minetest-Shaderpack#3]
1. Clone this repo
2. Set `shader_pack` to the path of this repo in `minetest.conf` for Luanti 5.8.0

Top of debug.txt after loading an existing Minetest Game world with the shaders enabled:

```
2024-12-06 20:51:25: [Main]: Automatically selecting world at [C:\Users\markw\myStuff\games\minetest-5.8.0-win64\bin\..\worlds\MTG]
2024-12-06 20:51:27: ACTION[Main]: World at [C:\Users\markw\myStuff\games\minetest-5.8.0-win64\bin\..\worlds\MTG]
2024-12-06 20:51:27: ACTION[Main]: Server for gameid="minetest" listening on 127.0.0.1:50665.
2024-12-06 20:51:27: ERROR[Main]: Irrlicht: GLSL (> 2.x) shader failed to compile: shaderType: 35632
2024-12-06 20:51:27: ERROR[Main]: Irrlicht: Fragment shader failed to compile with the following errors:
ERROR: 0:450: error(#143) Undeclared identifier: applyPerspectiveDistortion
ERROR: 0:450: error(#143) Undeclared identifier: m_ShadowViewProj
ERROR: 0:450: error(#202) No matching overloaded function found: applyPerspectiveDistortion
ERROR: 0:450: error(#216) Vector field selection out of range "xyz"
ERROR: 0:451: error(#143) Undeclared identifier: getHardShadow
ERROR: 0:451: error(#143) Undeclared identifier: ShadowMapSampler
ERROR: 0:451: error(#202) No matching overloaded function found: getHardShadow
ERROR: 0:480: error(#143) Undeclared identifier: fnoise
ERROR: 0:480: error(#202) No matching overloaded function found: fnoise
ERROR: 0:481: error(#202) No matching overloaded function found: fnoise
ERROR: 0:482: error(#202) No matching overloaded function found: fnoise
ERROR: 0:486: error(#143) Undeclared identifier: v_LightDirection
ERROR: 0:486: error(#202) No matching overloaded function found: dot
ERROR: error(#273) 13 compilation errors.  No code generated
```

Seems some shaders are applied, but not in a good way:

![image](https://github.com/user-attachments/assets/abb4babb-f545-4925-aa71-51e783d49f82)

**Comment by mark-wiemer** [comment]
Luanti 5.10.0 also fails, very similar, but crashes Luanti instead of loading the shaded game:

```
2024-12-06 20:54:49: ACTION[ServerStart]: World at [C:\Users\markw\myStuff\games\Luanti\bin\..\worlds\MTG]
2024-12-06 20:54:49: ACTION[ServerStart]: Server for gameid="minetest" listening on 127.0.0.1:61485.
2024-12-06 20:54:49: ERROR[Main]: Irrlicht: GLSL (> 2.x) shader failed to compile: shaderType: 35632
2024-12-06 20:54:49: ERROR[Main]: Irrlicht: Fragment shader failed to compile with the following errors:
ERROR: 0:450: error(#143) Undeclared identifier: applyPerspectiveDistortion
ERROR: 0:450: error(#143) Undeclared identifier: m_ShadowViewProj
ERROR: 0:450: error(#202) No matching overloaded function found: applyPerspectiveDistortion
ERROR: 0:450: error(#216) Vector field selection out of range "xyz"
ERROR: 0:451: error(#143) Undeclared identifier: getHardShadow
ERROR: 0:451: error(#143) Undeclared identifier: ShadowMapSampler
ERROR: 0:451: error(#202) No matching overloaded function found: getHardShadow
ERROR: 0:480: error(#143) Undeclared identifier: fnoise
ERROR: 0:480: error(#202) No matching overloaded function found: fnoise
ERROR: 0:481: error(#202) No matching overloaded function found: fnoise
ERROR: 0:482: error(#202) No matching overloaded function found: fnoise
ERROR: 0:486: error(#143) Undeclared identifier: v_LightDirection
ERROR: 0:486: error(#202) No matching overloaded function found: dot
ERROR: error(#273) 13 compilation errors.  No code generated


2024-12-06 20:54:49: ERROR[Main]: generate_shader(): failed to generate "nodes_shader", addHighLevelShaderMaterial failed.
```

**Comment by therandompersonn** [comment]
for me, i got 
```
2024-12-31 10:57:28: ERROR[Main]: Failed to compile the "nodes_shader" shader.
2024-12-31 10:57:28: ERROR[Main]: Check debug.txt for details.
```

on 5.11

**Comment by GefullteTaubenbrust2** [comment]
> for me, i got
> 
> ```
> 2024-12-31 10:57:28: ERROR[Main]: Failed to compile the "nodes_shader" shader.
> 2024-12-31 10:57:28: ERROR[Main]: Check debug.txt for details.
> ```
> 
> on 5.11

It won't work on anything but 5.8.

I'm not maintaining this anymore by the way, most of these effects will become part of the game or already have anyway.
